name: CAST Coverage Mapper

on:
  workflow_dispatch: {}

permissions:
  id-token: write

jobs:
  cast-coverage:
    uses: manchester-fme/CAST/.github/workflows/coverage-mapper.yml@feature/parametric-coverage-fuzzer
    with:
      solver: cvc5
      repo_url: ${{ github.server_url }}/${{ github.repository }}
      solver_dir: cvc5/cast-profile
    secrets: inherit
